# Node (https://hub.docker.com/_/node)
FROM node:22.6.0-slim

# TypeScript Language Server
# (https://github.com/typescript-language-server/typescript-language-server)
RUN npm install -g typescript typescript-language-server
