# Node (https://hub.docker.com/_/node)
FROM node:22.21.1-alpine3.21

# TypeScript Language Server
# (https://github.com/typescript-language-server/typescript-language-server)
RUN npm install -g typescript typescript-language-server
