model:
  default: glm-5
  provider: opencode-go
  base_url: https://opencode.ai/zen/go/v1
  api_mode: chat_completions
agent:
  max_turns: 150
  disabled_toolsets: '["browser","clarify","code_execution","computer_use","context_engine","cronjob","delegation","discord","discord_admin","feishu_doc","feishu_drive","homeassistant","image_gen","kanban","project","search","session_search","skills","spotify","todo","tts","video","video_gen","vision","web","x_search","yuanbao"]'
compression:
  enabled: true
display:
  tool_progress: all
memory:
  memory_enabled: true
  user_profile_enabled: true
_config_version: 33
mcp_servers:
  gitlab:
    url: http://gitlab-mcp:3002/mcp
    headers:
      Authorization: Bearer ${STREAMABLE_HTTP_AUTH_TOKEN}
  github:
    url: https://api.githubcopilot.com/mcp/
    headers:
      Authorization: Bearer ${GITHUB_PERSONAL_ACCESS_TOKEN}
platform_toolsets:
  cli: '["file","terminal"]'
smart_model_routing:
  enabled: false
session_reset:
  mode: none
known_plugin_toolsets:
  cli:
    - spotify
onboarding:
  seen:
    tool_progress_prompt: true
    busy_input_prompt: true
