services:
  common:
    image: scratch
    volumes:
      - ${PWD}:${PWD}
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    working_dir: ${PWD}
    user: ${UID}:${GID}
    tty: true
  bashls:
    image: genjiohara/bashls
    extends: common
  clangd:
    image: lspcontainers/clangd-language-server
    extends: common
  gnuplot:
    image: genjiohara/gnuplot
    extends: common
  hls:
    image: genjiohara/haskell-language-server
    environment:
      - CABAL_DIR=${PWD}/.cabal
    extends: common
  lua_ls:
    image: lspcontainers/lua-language-server
    extends: common
  node-tsserver:
    image: genjiohara/node-tsserver
    extends: common
  pyright:
    image: lspcontainers/pyright-langserver
    extends: common
  rye:
    image: genjiohara/rye
    extends: common
  texlab:
    image: genjiohara/texlab
    extends: common
