services:
  clangd:
    image: lspcontainers/clangd-language-server
    volumes:
      - ${PWD}:${PWD}
    working_dir: ${PWD}
    tty: true
  gnuplot:
    image: genjiohara/gnuplot
    volumes:
      - ${PWD}:${PWD}
    working_dir: ${PWD}
    tty: true
  hls:
    image: genjiohara/haskell-language-server
    container_name: haskell-pso-hls
    volumes:
      - ${PWD}:${PWD}
    working_dir: ${PWD}
    environment:
      - CABAL_DIR=${PWD}/.cabal
    tty: true
  lua_ls:
    image: lspcontainers/lua-language-server
    volumes:
      - ${PWD}:${PWD}
    working_dir: ${PWD}
    tty: true
  node:
    image: node:22.4.1-slim
    volumes:
      - ${PWD}:${PWD}
    working_dir: ${PWD}
    tty: true
  pyright:
    image: lspcontainers/pyright-langserver
    volumes:
      - ${PWD}:${PWD}
    working_dir: ${PWD}
    tty: true
  rye:
    image: genjiohara/rye
    volumes:
      - ${PWD}:${PWD}
    working_dir: ${PWD}
    tty: true
  texlab:
    image: genjiohara/texlab
    volumes:
      - ${PWD}:${PWD}
    working_dir: ${PWD}
    tty: true
