#!/bin/sh
# shellcheck enable=all

ROOT="$(cd "$(dirname "$0")" && pwd)"
SCRIPT="curl https://sh.rustup.rs -sSf | RUSTUP_INIT_SKIP_PATH_CHECK=yes sh"
"${ROOT}"/scripts/healthcheck.sh "$(basename "$0")" "${SCRIPT}"
RETVAL=$?
[ "${RETVAL}" -eq 0 ] && docker compose -f ${HOME}/.dockerscripts/compose.yaml run --rm rust cargo "$@"
